//
// Chinese menu support header file
//

#ifndef UV_K5_FIRMWARE_CUSTOM_CHINESE_H
#define UV_K5_FIRMWARE_CUSTOM_CHINESE_H

#include "font.h"

#if ENABLE_CHINESE_FULL == 4 && !defined(ENABLE_ENGLISH)
// Chinese mode - use losehu custom encoding

#define SQL         "\xB3\xB4\xB5\xB6"
#define DWMode      "\x06\x0E\x0C\x89"
#define STEP        "\x01\x02\x03\x04"
#define Power       "\x0E\xC8\xDF\x04"
#define RxDCS       "\x05\x06\x07\x08\x09\x0B"
#define RxCTCS      "\x05\x06\x0C\x0D\x09\x0B"
#define TxDCS       "\x0E\x0F\x07\x08\x09\x0B"
#define TxCTCS      "\x0E\x0F\x0C\x0D\x09\x0B"
#define TxDir       "\x03\x10\x11\x12"
#define TxOffs      "\x03\x10\x03\x04"
#define W_N         "\x03\x10\x11\x12"
#define Scramb      "\x13\x14"
#define BzLock      "\x15\x16\x17\x0E"
#define Mode        "\x18\x19"
#define TXLock      "\x15\x16\x17\x0E"
#define ChSave      "\x1A\x1B\x1C\x1D"
#define ChDele      "\x1E\x1F\x1C\x1D"
#define ChName      "\x7F\x80\x1C\x1D"
#define F1Shrt      "\xA9\xA2\x31\xDB\xA1"
#define F1Long      "\xA9\xA2\x31\xD9\xA1"
#define F2Shrt      "\xA9\xA2\x32\xDB\xA1"
#define F2Long      "\xA9\xA2\x32\xD9\xA1"
#define MLong       "M\xD9\xA1"
#define BatSav      "\x8C\x8D\x0C\x89"
#define BatTxt      "\x8D\xBA\xBC\xBD"
#define Mic         "\x8E\x8F\x90\x91\x92"
#define ChDisp      "\x1C\x1D\x93\x94\x0C\x89"
#define POnMsg      "\xC7\x1C\x1D\n\x05\x06\x0E\xC8"
#define BLTime      "\x95\x96\x97\x98"
#define BLMax       "\x97\x98\x99\x9A"
#define Beep        "\x00\x00\x00\x00"
#define Roger       "\x9B\x9C\x0B"
#define STE         "\x9C\x0B\x9D\x1F"
#define RP_STE      "\x9E\x9F\xA0\x9C\x0B\x9D\x1F"
#define Call1       "\xA1\xA2\xA3\xA4"
#define VOX         "\x00\x00\x00\x00"
#define SysInf      "\xCF\xB5\xCD\xB3\xD0\xC5\xCF\xA2"
#define BatVol      "\x8D\xBA\xBB\x18"
#define SetPwr      "\x00\x00\x00\x00"
#define SetCtr      "\x00\x00\x00\x00"
#define SetInv      "\x00\x00\x00\x00"
#define SetLck      "\x00\x00\x00\x00"
#define SetMet      "\x00\x00\x00\x00"
#define SetGui      "\x00\x00\x00\x00"
#define SetNFM      "\x00\x00\x00\x00"
#define SetVol      "\x00\x00\x00\x00"
#define SetKey      "\x00\x00\x00\x00"
#define SetNWR      "\x00\x00\x00\x00"
#define FLock       "\x03\xB7\xB8\xB9"
#define BatCal      "\x8D\xBA\xBB\x18"
#define BatTyp      "\x8D\xBA\xBC\xBD"
#define Reset       "\xBE\x07\x88\xAC"

// Sub-menu items
#define WIDE        "\x03\x10\x11\x12"
#define NARROW      "\x03\x10\x11\x12"
#define OFF         "\xC1\xC2"
#define ON          "\xC3\xC4"
#define NA          "\x00\x00\x00\x00"

#else
// English mode - keep original English text
#define SQL         "SQL"
#define DWMode      "DWMode"
#define STEP        "Step"
#define Power       "Power"
#define RxDCS       "RxDCS"
#define RxCTCS      "RxCTCS"
#define TxDCS       "TxDCS"
#define TxCTCS      "TxCTCS"
#define TxDir       "TxDir"
#define TxOffs      "TxOffs"
#define W_N         "W/N"
#define Scramb      "Scramb"
#define BzLock      "BzLock"
#define Mode        "Mode"
#define TXLock      "TXLock"
#define ChSave      "ChSave"
#define ChDele      "ChDele"
#define ChName      "ChName"
#define F1Shrt      "F1Shrt"
#define F1Long      "F1Long"
#define F2Shrt      "F2Shrt"
#define F2Long      "F2Long"
#define MLong       "M Long"
#define BatSav      "BatSav"
#define BatTxt      "BatTxt"
#define Mic         "Mic"
#define ChDisp      "ChDisp"
#define POnMsg      "POnMsg"
#define BLTime      "BLTime"
#define BLMax       "BLMax"
#define Beep        "Beep"
#define Roger       "Roger"
#define STE         "STE"
#define RP_STE      "RP STE"
#define Call1       "1 Call"
#define VOX         "VOX"
#define SysInf      "SysInf"
#define BatVol      "BatVol"
#define SetPwr      "SetPwr"
#define SetCtr      "SetCtr"
#define SetInv      "SetInv"
#define SetLck      "SetLck"
#define SetMet      "SetMet"
#define SetGui      "SetGui"
#define SetNFM      "SetNFM"
#define SetVol      "SetVol"
#define SetKey      "SetKey"
#define SetNWR      "SetNWR"
#define FLock       "F Lock"
#define BatCal      "BatCal"
#define BatTyp      "BatTyp"
#define Reset       "Reset"

// Sub-menu items
#define WIDE        "WIDE"
#define NARROW      "NARROW"
#define OFF         "OFF"
#define ON          "ON"
#define NA          "N/A"

#endif // ENABLE_CHINESE_FULL

#endif // UV_K5_FIRMWARE_CUSTOM_CHINESE_H