//
// Chinese menu support header file
//

#ifndef UV_K5_FIRMWARE_CUSTOM_CHINESE_H
#define UV_K5_FIRMWARE_CUSTOM_CHINESE_H

#include "font.h"

#ifdef ENABLE_CHINESE
// Chinese mode - use GB2312 encoding

#define SQL         "\xBE\xB2\xD4\xEB"
#define DWMode      "\xCB\xAB\xB9\xA4\xC4\xA3\xCA\xBD"
#define STEP        "\xB2\xBD\xBD\xF8"
#define Power       "\xB9\xA6\xC2\xCA"
#define RxDCS       "\xBD\xD3\xCA\xD5\xD1\xC7\xD2\xF4"
#define RxCTCS      "\xBD\xD3\xCA\xD5\xD1\xC7\xD2\xF4"
#define TxDCS       "\xB7\xA2\xCB\xCD\xD1\xC7\xD2\xF4"
#define TxCTCS      "\xB7\xA2\xCB\xCD\xD1\xC7\xD2\xF4"
#define TxDir       "\xB7\xA2\xCB\xCD\xB7\xBD\xCF\xF2"
#define TxOffs      "\xB7\xA2\xCB\xCD\xC6\xAB\xD2\xC6"
#define W_N         "\xBF\xED\xD5\xAD"
#define Scramb      "\xC8\xC5\xC6\xB5"
#define BzLock      "\xB7\xA6\xC3\xA6\xCB\xF8\xB6\xA8"
#define Mode        "\xC4\xA3\xCA\xBD"
#define TXLock      "\xB7\xA2\xCB\xCD\xCB\xF8\xB6\xA8"
#define ChSave      "\xC6\xB5\xB5\xC0\xB1\xA3\xB4\xE6"
#define ChDele      "\xC6\xB5\xB5\xC0\xC9\xBE\xB3\xFD"
#define ChName      "\xC6\xB5\xB5\xC0\xC3\xFB\xB3\xC6"
#define F1Shrt      "F1\xB6\xCC\xB0\xB4"
#define F1Long      "F1\xB3\xA4\xB0\xB4"
#define F2Shrt      "F2\xB6\xCC\xB0\xB4"
#define F2Long      "F2\xB3\xA4\xB0\xB4"
#define MLong       "M\xB3\xA4\xB0\xB4"
#define BatSav      "\xB5\xE7\xB3\xD8\xCA\xA1\xB5\xE7"
#define BatTxt      "\xB5\xE7\xB3\xD8\xCE\xC4\xB1\xBE"
#define Mic         "\xC2\xF3\xBF\xCB\xB7\xE7"
#define ChDisp      "\xC6\xB5\xB5\xC0\xCF\xD4\xCA\xBE"
#define POnMsg      "\xBF\xAA\xBB\xFA\xCF\xD4\xCA\xBE"
#define BLTime      "\xB1\xB3\xB9\xE2\xCA\xB1\xBC\xE4"
#define BLMax       "\xB1\xB3\xB9\xE2\xC1\xC1\xB6\xC8"
#define Beep        "\xCC\xE1\xCA\xBE\xD2\xF4"
#define Roger       "\xCE\xB2\xD2\xF4"
#define STE         "\xD1\xC7\xD2\xF4\xC9\xE8\xD6\xC3"
#define RP_STE      "\xD6\xD0\xBC\xCC\xD1\xC7\xD2\xF4"
#define Call1       "\xBD\xF8\xC8\xEB\xBA\xF4\xBD\xD0"
#define VOX         "\xC9\xF9\xBF\xD8\xB7\xA2\xC9\xE4"
#define SysInf      "\xCF\xB5\xCD\xB3\xD0\xC5\xCF\xA2"
#define BatVol      "\xB5\xE7\xB3\xD8\xB5\xE7\xD1\xB9"
#define SetPwr      "\xC9\xE8\xD6\xC3\xB9\xA6\xC2\xCA"
#define SetCtr      "\xC9\xE8\xD6\xC3\xD6\xD0\xD0\xC4"
#define SetInv      "\xC9\xE8\xD6\xC3\xB7\xB4\xD7\xAA"
#define SetLck      "\xC9\xE8\xD6\xC3\xCB\xF8\xB6\xA8"
#define SetMet      "\xC9\xE8\xD6\xC3\xCF\xD4\xCA\xBE"
#define SetGui      "\xC9\xE8\xD6\xC3\xBD\xE7\xC3\xE6"
#define SetNFM      "\xC9\xE8\xD6\xC3\xD5\xAD\xB4\xF8"
#define SetVol      "\xC9\xE8\xD6\xC3\xD2\xF4\xC1\xBF"
#define SetKey      "\xC9\xE8\xD6\xC3\xB0\xB4\xBC\xFC"
#define SetNWR      "\xC9\xE8\xD6\xC3\xCC\xEC\xC6\xF8"
#define FLock       "\xC6\xB5\xC2\xCA\xCB\xF8\xB6\xA8"
#define BatCal      "\xB5\xE7\xB3\xD8\xD0ё\xBC\xCA\xB5"
#define BatTyp      "\xB5\xE7\xB3\xD8\xC0\xE0\xD0\xCD"
#define Reset       "\xBB\xD6\xB8\xB4\xB3\xF6\xB3\xA7"

// Sub-menu items
#define WIDE        "\xBF\xED\xB4\xF8"
#define NARROW      "\xD5\xAD\xB4\xF8"
#define OFF         "\xB9\xD8\xB1\xD5"
#define ON          "\xBF\xAA\xC6\xF4"
#define NA          "\xCE\xDE\xD0\xA7"

#else
// English mode - keep original English text
#define SQL         "SQL"
#define DWMode      "DWMode"
#define STEP        "Step"
#define Power       "Power"
#define RxDCS       "RxDCS"
#define RxCTCS      "RxCTCS"
#define TxDCS       "TxDCS"
#define TxCTCS      "TxCTCS"
#define TxDir       "TxDir"
#define TxOffs      "TxOffs"
#define W_N         "W/N"
#define Scramb      "Scramb"
#define BzLock      "BzLock"
#define Mode        "Mode"
#define TXLock      "TXLock"
#define ChSave      "ChSave"
#define ChDele      "ChDele"
#define ChName      "ChName"
#define F1Shrt      "F1Shrt"
#define F1Long      "F1Long"
#define F2Shrt      "F2Shrt"
#define F2Long      "F2Long"
#define MLong       "M Long"
#define BatSav      "BatSav"
#define BatTxt      "BatTxt"
#define Mic         "Mic"
#define ChDisp      "ChDisp"
#define POnMsg      "POnMsg"
#define BLTime      "BLTime"
#define BLMax       "BLMax"
#define Beep        "Beep"
#define Roger       "Roger"
#define STE         "STE"
#define RP_STE      "RP STE"
#define Call1       "1 Call"
#define VOX         "VOX"
#define SysInf      "SysInf"
#define BatVol      "BatVol"
#define SetPwr      "SetPwr"
#define SetCtr      "SetCtr"
#define SetInv      "SetInv"
#define SetLck      "SetLck"
#define SetMet      "SetMet"
#define SetGui      "SetGui"
#define SetNFM      "SetNFM"
#define SetVol      "SetVol"
#define SetKey      "SetKey"
#define SetNWR      "SetNWR"
#define FLock       "F Lock"
#define BatCal      "BatCal"
#define BatTyp      "BatTyp"
#define Reset       "Reset"

// Sub-menu items
#define WIDE        "WIDE"
#define NARROW      "NARROW"
#define OFF         "OFF"
#define ON          "ON"
#define NA          "N/A"

#endif // ENABLE_CHINESE

#endif // UV_K5_FIRMWARE_CUSTOM_CHINESE_H