name: Build Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 添加这一行以支持手动触发
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile firmware
      run: |
        chmod +x compile-with-docker.sh
        ./compile-with-docker.sh custom

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-artifact
        path: compiled-firmware/f4hwn.packed.bin
